import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import { jsPluginSettings, selectJsPlugins } from "ultracite/oxlint/js-plugins";
import next from "ultracite/oxlint/next";
import nextJsPlugins from "ultracite/oxlint/next/js-plugins";
import react from "ultracite/oxlint/react";

const jsPlugins = selectJsPlugins(["react-doctor"]);

export default defineConfig({
  extends: [core, next, react, nextJsPlugins, jsPlugins],
  // components/ui is generated by shadcn; regenerate with `just ui <name>` instead of editing.
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    "components/ui/**",
    ".next/**",
  ],
  jsPlugins: jsPlugins.jsPlugins,
  rules: {
    // Next.js conventions (default-exported pages/layouts, hoisted helpers) use function declarations.
    "func-style": "off",
    "no-use-before-define": ["error", { functions: false }],
    "react/function-component-definition": "off",
  },
  settings: jsPluginSettings,
});
